version: "3.3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ~/dockerdata/elasticsearch:/usr/share/elasticsearch/data/

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch